"""initial catalogue schema

Revision ID: 3a48eed79c3c
Revises:
Create Date: 2026-06-05 12:39:29.803200

Baseline catalogue (ADD 09 §2). All tables are portable except ``fs_entry``, which on
PostgreSQL is created as a two-level LIST-partitioned table — partitioned by ``host_id``
and sub-partitioned by ``volume_id`` (ADD 09 §8) — with a ``text_pattern_ops`` index on
``path`` so the read layer's LIKE-prefix subtree queries (AR-0015) stay index-backed.

Partition-key rule: PostgreSQL requires every unique/primary-key constraint on a
partitioned table to contain all partition-key columns. The PK is therefore widened to
``(id, host_id, volume_id)`` and the agent-identity uniqueness stays ``(host_id,
volume_id, inode)`` — which also makes it a valid ``ON CONFLICT`` target for the ingest
upsert on a partitioned table. The ORM keeps ``id`` as its sole mapped key; the wider DB
PK is invisible to it. On SQLite (dev/test) ``fs_entry`` is a plain table so the suite is
unaffected.

Per-host / per-volume partitions are created dynamically at ingest time for pruning; this
migration provisions only the partitioned parent plus a DEFAULT → DEFAULT catch-all chain
so any ``(host_id, volume_id)`` routes without a pre-created partition.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a48eed79c3c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_fs_entry_postgres() -> None:
    """Two-level LIST-partitioned ``fs_entry`` with a text_pattern_ops path index."""
    op.execute(
        """
        CREATE TABLE fs_entry (
            id                    integer GENERATED BY DEFAULT AS IDENTITY,
            host_id               integer NOT NULL,
            volume_id             integer NOT NULL,
            parent_id             integer,
            name                  varchar(1024) NOT NULL,
            path                  varchar(4096) NOT NULL,
            depth                 integer NOT NULL,
            is_dir                boolean NOT NULL,
            is_symlink            boolean NOT NULL,
            size_logical          bigint  NOT NULL,
            size_on_disk          bigint  NOT NULL,
            mtime                 double precision NOT NULL,
            ctime                 double precision NOT NULL,
            uid                   integer NOT NULL,
            gid                   integer NOT NULL,
            inode                 bigint  NOT NULL,
            flags                 json    NOT NULL,
            last_seen_snapshot_id integer,
            CONSTRAINT pk_fs_entry PRIMARY KEY (id, host_id, volume_id),
            CONSTRAINT uq_fs_entry_identity UNIQUE (host_id, volume_id, inode),
            CONSTRAINT fk_fs_entry_host   FOREIGN KEY (host_id)   REFERENCES host (id),
            CONSTRAINT fk_fs_entry_volume FOREIGN KEY (volume_id) REFERENCES volume (id)
        ) PARTITION BY LIST (host_id);
        """
    )
    # DEFAULT host partition, itself sub-partitioned by volume_id, with a DEFAULT
    # sub-partition: guarantees every (host_id, volume_id) has a landing partition before
    # the per-host/per-volume partitions are provisioned at ingest time.
    op.execute(
        "CREATE TABLE fs_entry_hdefault PARTITION OF fs_entry DEFAULT "
        "PARTITION BY LIST (volume_id);"
    )
    op.execute("CREATE TABLE fs_entry_hdefault_vdefault PARTITION OF fs_entry_hdefault DEFAULT;")

    # Partitioned indexes (propagate to all current and future partitions).
    op.execute("CREATE INDEX ix_fs_entry_host_id ON fs_entry (host_id);")
    op.execute("CREATE INDEX ix_fs_entry_volume_id ON fs_entry (volume_id);")
    # text_pattern_ops keeps `path LIKE 'prefix%'` (drill-down, AR-0015) index-backed even
    # under a non-C collation.
    op.execute("CREATE INDEX ix_fs_entry_path ON fs_entry (path text_pattern_ops);")


def _create_fs_entry_plain() -> None:
    """Plain (non-partitioned) ``fs_entry`` for SQLite/dev — schema parity, no partitioning."""
    op.create_table(
        "fs_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_dir", sa.Boolean(), nullable=False),
        sa.Column("is_symlink", sa.Boolean(), nullable=False),
        sa.Column("size_logical", sa.BigInteger(), nullable=False),
        sa.Column("size_on_disk", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.Float(), nullable=False),
        sa.Column("ctime", sa.Float(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("gid", sa.Integer(), nullable=False),
        sa.Column("inode", sa.BigInteger(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("last_seen_snapshot_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["host.id"]),
        sa.ForeignKeyConstraint(["volume_id"], ["volume.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "volume_id", "inode", name="uq_fs_entry_identity"),
    )
    op.create_index(op.f("ix_fs_entry_host_id"), "fs_entry", ["host_id"], unique=False)
    op.create_index(op.f("ix_fs_entry_path"), "fs_entry", ["path"], unique=False)
    op.create_index(op.f("ix_fs_entry_volume_id"), "fs_entry", ["volume_id"], unique=False)


def upgrade() -> None:
    op.create_table(
        "host",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("os", sa.String(length=255), nullable=True),
        sa.Column("agent_version", sa.String(length=64), nullable=True),
        sa.Column("cert_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cert_fingerprint"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "volume",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("mountpoint", sa.String(length=4096), nullable=False),
        sa.Column("fs_type", sa.String(length=64), nullable=False),
        sa.Column("device", sa.String(length=255), nullable=False),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column("raid_role", sa.String(length=255), nullable=True),
        sa.Column("pool", sa.String(length=255), nullable=True),
        sa.Column("dataset", sa.String(length=255), nullable=True),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column("used", sa.BigInteger(), nullable=False),
        sa.Column("free", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["host_id"], ["host.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "mountpoint", name="uq_volume_host_mount"),
    )

    if op.get_bind().dialect.name == "postgresql":
        _create_fs_entry_postgres()
    else:
        _create_fs_entry_plain()

    op.create_table(
        "size_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("total_size_logical", sa.BigInteger(), nullable=False),
        sa.Column("total_size_on_disk", sa.BigInteger(), nullable=False),
        sa.Column("file_count", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["volume_id"], ["volume.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_size_history_volume_id"), "size_history", ["volume_id"], unique=False)
    op.create_table(
        "snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column(
            "started", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("finished", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_size", sa.BigInteger(), nullable=False),
        sa.Column("file_count", sa.BigInteger(), nullable=False),
        sa.Column("warning_ack", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["host.id"]),
        sa.ForeignKeyConstraint(["volume_id"], ["volume.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subtree_rollup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("total_size_logical", sa.BigInteger(), nullable=False),
        sa.Column("total_size_on_disk", sa.BigInteger(), nullable=False),
        sa.Column("file_count", sa.BigInteger(), nullable=False),
        sa.Column("dir_count", sa.BigInteger(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["volume_id"], ["volume.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volume_id", "path", name="uq_rollup_vol_path"),
    )
    op.create_index(
        op.f("ix_subtree_rollup_volume_id"), "subtree_rollup", ["volume_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_subtree_rollup_volume_id"), table_name="subtree_rollup")
    op.drop_table("subtree_rollup")
    op.drop_table("snapshot")
    op.drop_index(op.f("ix_size_history_volume_id"), table_name="size_history")
    op.drop_table("size_history")
    if op.get_bind().dialect.name == "postgresql":
        # Dropping the partitioned parent cascades to its partitions and indexes.
        op.execute("DROP TABLE IF EXISTS fs_entry CASCADE;")
    else:
        op.drop_index(op.f("ix_fs_entry_volume_id"), table_name="fs_entry")
        op.drop_index(op.f("ix_fs_entry_path"), table_name="fs_entry")
        op.drop_index(op.f("ix_fs_entry_host_id"), table_name="fs_entry")
        op.drop_table("fs_entry")
    op.drop_table("volume")
    op.drop_table("host")
